# -*- coding: utf-8 -*-
"""Untitled42.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eJEyTZP00jIJSFoxHw9ZS4dcqr2xmk73
"""

# -*- coding: utf-8 -*-
"""Model-3-Linear_interp_lag7_5-models-ActualOnly.ipynb
---
วัตถุประสงค์: ปรับปรุงการประเมินผลลัพธ์ (Metrics) โดยคำนวณจากราคาปิดจริง (Actual Close) เท่านั้น
"""

# ----------------------------------------------------
# 0. ติดตั้งและนำเข้าไลบรารี
# ----------------------------------------------------
!pip install pandas_market_calendars
!pip install yfinance scikit-learn xgboost matplotlib tqdm

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime, timedelta
import pandas_market_calendars as mcal
from tqdm import tqdm

# ไลบรารีสำหรับ Machine Learning
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler

# ------------------------------
# 0. กำหนด list หุ้นทั้งหมด และช่วงวันที่
# ------------------------------
tickers = ["AAPL", "AMD", "AVGO", "GOOG", "GOOGL", "META", "MSFT", "NVDA"]
start_date = datetime(2019, 1, 1)
end_date   = datetime(2024, 12, 31)
all_data_list = []

# ------------------------------
# 1. ดาวน์โหลดข้อมูลหุ้นทั้งหมด
# ------------------------------
for ticker in tickers:
    print(f"📥 Downloading {ticker} ...")
    data = yf.download(ticker, start=start_date.strftime('%Y-%m-%d'), end=end_date.strftime('%Y-%m-%d'))

    if data.empty:
        print(f"❌ No data for {ticker}")
        continue

    data.reset_index(inplace=True)

    # จัดการและทำความสะอาดชื่อคอลัมน์
    if isinstance(data.columns, pd.MultiIndex):
        data.columns = [' '.join(col).strip() if isinstance(col, tuple) else col for col in data.columns.values]

    def clean_columns(cols):
        cleaned = []
        for col in cols:
            if 'Date' in col: cleaned.append('Date')
            else: cleaned.append(col.split()[0])
        return cleaned

    data.columns = clean_columns(data.columns)
    data['Symbol'] = ticker.upper()

    wanted_cols = ['Date', 'Open','High','Low','Close', 'Volume', 'Symbol']
    data = data[[col for col in wanted_cols if col in data.columns]]
    all_data_list.append(data)

flat_df = pd.concat(all_data_list, ignore_index=True)
print("✅ ดาวน์โหลดและรวมข้อมูลสำเร็จ")

# ----------------------------------------------------
# 2. จัดการวันหยุด + Nearest Neighbor Interpolation และสร้าง Flag
# ----------------------------------------------------
# 1. สร้าง continuous date range
all_dates = pd.DataFrame({'Date': pd.date_range(flat_df['Date'].min(), flat_df['Date'].max())})
symbols = flat_df['Symbol'].unique()
expanded_list = []
for sym in symbols:
    temp = all_dates.copy()
    temp['Symbol'] = sym
    expanded_list.append(temp)
all_dates_symbols = pd.concat(expanded_list, ignore_index=True)

# 2. merge กับ flat_df (ตอนนี้ 'Close' มี NaN ในวันหยุด)
full_df = all_dates_symbols.merge(flat_df, on=['Date','Symbol'], how='left')

# **⭐️ ส่วนที่เพิ่ม: สร้าง Flag สำหรับราคาปิดจริง (Actual Close) ⭐️**
# Flag 1 ถ้า Close มีค่า (ไม่เป็น NaN) -> เป็นราคาปิดจริง
# Flag 0 ถ้า Close เป็น NaN -> เป็นวันหยุด (จะถูกเติมค่าในขั้นตอนถัดไป)
full_df['Is_Actual_Close'] = full_df['Close'].notna().astype(float)


# 3. เติมค่าว่าง Close ด้วย nearest (Interpolation)
price_cols = ['Close']
for col in price_cols:
    full_df[col] = full_df.groupby('Symbol')[col].transform(
        lambda x: x.interpolate(method='nearest')
    )
# กำหนดให้ OHLCV ที่เหลือเป็น 0 หรือ NaN
full_df[['Open','High','Low','Volume']] = full_df[['Open','High','Low','Volume']].fillna(0)

print("\n✅ จัดการวันหยุดและ Nearest Neighbor Interpolation เสร็จสิ้น")

# ----------------------------------------------------
# 3. สร้าง Lag-7 Features และ Target
# ----------------------------------------------------
lag_cols = []
for lag in range(1, 8):
    col_name = f'Close_lag{lag}'
    full_df[col_name] = full_df.groupby('Symbol')['Close'].shift(lag)
    lag_cols.append(col_name)

# 9. สร้าง Target: Close ของวันถัดไป (ใช้ Close ที่ Interpolate แล้ว)
full_df['Close_next'] = full_df.groupby('Symbol')['Close'].shift(-1)

# **⭐️ ส่วนที่เพิ่ม: Shift Flag เพื่อให้สอดคล้องกับ Target ⭐️**
# Is_Actual_Target = 1.0 ถ้า Close_next เป็นราคาจริง (ที่เราต้องการประเมิน)
full_df['Is_Actual_Target'] = full_df.groupby('Symbol')['Is_Actual_Close'].shift(-1)

# กำหนด Feature Matrix X
X_cols = lag_cols
print("\n✅ สร้าง Lag-7 Features และ Target (Close_next) เสร็จสิ้น")

# ----------------------------------------------------
# 4. Sliding Window (70/15/15) และ Model Training/Evaluation
# ----------------------------------------------------
window_train = 0.7
window_test = 0.15

# เตรียมโมเดล (5 โมเดล)
models = {
    'Linear': LinearRegression(),
    'RandomForest': RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    'GradientBoosting': GradientBoostingRegressor(n_estimators=100, random_state=42),
    'XGBoost': XGBRegressor(n_estimators=100, random_state=42, verbosity=0, n_jobs=-1),
    'SVR': SVR()
}

# ตัวแปรเก็บผลลัพธ์ทั้งหมด
all_results = []
window_predictions_full = []
model_name = "Linearinterp_lag7_ActualOnly"

# Loop แต่ละ Symbol
for sym in tqdm(symbols, desc="Training models with Sliding Window (Actual Only)"):
    df_sym = full_df[full_df['Symbol'] == sym].sort_values('Date').reset_index(drop=True)

    # Feature, Target และ Flag
    data_ml = df_sym[['Date'] + X_cols + ['Close_next', 'Is_Actual_Target']].dropna().reset_index(drop=True)

    X_clean = data_ml[X_cols]
    y_clean = data_ml['Close_next']
    is_actual_target_clean = data_ml['Is_Actual_Target']
    date_clean = data_ml['Date']

    n = len(X_clean)
    step = int(n * window_test)
    start = 0
    window_id = 1

    # Sliding Window Loop
    while start + int(n * window_train) + step <= n:
        train_idx = range(start, start + int(n*window_train))
        test_idx  = range(start + int(n*window_train), start + int(n*window_train) + step)

        X_train = X_clean.iloc[train_idx].values
        y_train = y_clean.iloc[train_idx].values
        X_test  = X_clean.iloc[test_idx].values
        y_test  = y_clean.iloc[test_idx].values

        # ดึง Flag ของ Test Set
        is_actual_test = is_actual_target_clean.iloc[test_idx].values
        date_test = date_clean.iloc[test_idx].values

        # Scale Training set
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled  = scaler.transform(X_test)

        # Train & Evaluate ทุกโมเดล
        for name, model in models.items():
            model.fit(X_train_scaled, y_train)
            y_pred = model.predict(X_test_scaled)

            # **⭐️ ขั้นตอนการกรอง: ประเมินเฉพาะ Target ที่เป็นราคาจริงเท่านั้น (Is_Actual_Target = 1.0) ⭐️**

            actual_mask = (is_actual_test == 1.0)
            y_test_actual = y_test[actual_mask]
            y_pred_actual = y_pred[actual_mask]

            # ตรวจสอบว่ามีข้อมูลจริงเหลือสำหรับการประเมินหรือไม่
            if len(y_test_actual) > 0:
                 # คำนวณ Metrics บนข้อมูลจริงเท่านั้น
                 all_results.append({
                    'Symbol': sym,
                    'model': name,
                    'Window': window_id,
                    'start_idx': start,
                    'rmse': np.sqrt(mean_squared_error(y_test_actual, y_pred_actual)),
                    'mae': mean_absolute_error(y_test_actual, y_pred_actual),
                    'r2': r2_score(y_test_actual, y_pred_actual),
                    'Model Name': model_name
                 })

            # เก็บรายละเอียดการทำนาย (Predicted vs. Actual)
            temp_df = pd.DataFrame({
                'Date': date_test,
                'Symbol': sym,
                'Window': window_id,
                'model': name,
                'Actual_Close_next': y_test,
                'Predicted_Close_next': y_pred,
                'Is_Actual_Target': is_actual_test
            })
            window_predictions_full.append(temp_df)

        start += step
        window_id += 1

# แปลงเป็น DataFrame
results_df = pd.DataFrame(all_results)
window_predictions_df = pd.concat(window_predictions_full, axis=0).reset_index(drop=True)

print("\n✅ ฝึกฝนโมเดลและเก็บผลลัพธ์สำเร็จ")

# ----------------------------------------------------
# 5. สรุปและ Export ผลลัพธ์
# ----------------------------------------------------

# Export results_df (ผลลัพธ์ของทุก Window)
results_df.to_excel("results_ActualOnly_lag7.xlsx", index=False)
print("✅ Exported results (Actual Only) to results_ActualOnly_lag7.xlsx")

# สรุปผลลัพธ์ (Average Metrics)
average_results = results_df.groupby('model')[['rmse', 'mae', 'r2']].mean().reset_index()

# จัดรูปแบบตัวเลข
format_mapping = {
    'rmse': '{:,.4f}'.format,
    'mae': '{:,.4f}'.format,
    'r2': '{:,.4f}'.format
}
average_results_formatted = average_results.copy()
for col, formatter in format_mapping.items():
    average_results_formatted[col] = average_results_formatted[col].apply(formatter)

print("\n--- 📈 สรุปผลการประเมินโมเดล (Actual Dates Only) ---")
print(average_results_formatted)

# บันทึกผลสรุปค่าเฉลี่ยลงใน Excel
average_results.to_excel("average_results_ActualOnly_lag7.xlsx", index=False)
print("✅ บันทึกผลสรุปค่าเฉลี่ยลงใน average_results_ActualOnly_lag7.xlsx")

# Export รายละเอียดการทำนาย (Predicted vs. Actual) - รวมวันที่เติมค่าไว้ แต่มี Flag กำกับ
window_predictions_df.to_excel("predictions_full_details_ActualOnly_lag7.xlsx", index=False)
print("✅ Exported รายละเอียดการทำนาย (Predicted vs. Actual) to predictions_full_details_ActualOnly_lag7.xlsx")

print("\n--- การรันโค้ดทั้งหมดเสร็จสมบูรณ์ ---")

import pandas as pd
import matplotlib.pyplot as plt

# 1. อ่านไฟล์ Excel ที่มีรายละเอียดการทำนาย
file_path = "predictions_full_details_ActualOnly_lag7.xlsx"
try:
    predictions_df = pd.read_excel(file_path)
except FileNotFoundError:
    print(f"❌ Error: File not found at {file_path}. Please run the full code first.")
    # สร้าง DataFrame เปล่าเพื่อป้องกันโค้ดหยุดทำงาน
    predictions_df = pd.DataFrame()

if not predictions_df.empty:
    # 2. กำหนด Symbol และ Window ที่ต้องการแสดง
    TARGET_SYMBOL = 'AAPL' # เลือกหุ้นที่สนใจ

    # หาวินโดว์ ID สุดท้ายของ Symbol นั้นๆ เพื่อแสดงผลการทำนายล่าสุด
    max_window = predictions_df[predictions_df['Symbol'] == TARGET_SYMBOL]['Window'].max()

    # กรองข้อมูลเฉพาะ Symbol และ Window ที่เลือก
    plot_data = predictions_df[
        (predictions_df['Symbol'] == TARGET_SYMBOL) &
        (predictions_df['Window'] == max_window)
    ]

    if plot_data.empty:
        print(f"❌ No data found for {TARGET_SYMBOL} in Window {max_window}.")
    else:
        # เตรียมข้อมูลสำหรับการ Plotting
        # ใช้ Date เป็น Index
        plot_data = plot_data.set_index('Date').sort_index()

        # ดึงราคาจริง (Actual) - แก้ไขโดย reset_index ก่อน drop_duplicates เพื่อให้ 'Date' เป็นคอลัมน์
        actual_price = plot_data.reset_index().drop_duplicates(subset=['Date']).set_index('Date')['Actual_Close_next']

        # 3. สร้างกราฟ
        plt.figure(figsize=(14, 7))

        # Plot ราคาจริง (Actual)
        plt.plot(actual_price, label='Actual Close Price (Next Day)', color='black', linewidth=3)

        # Plot ค่าทำนายของแต่ละโมเดล
        models_to_plot = plot_data['model'].unique()

        for model_name in models_to_plot:
            model_predictions = plot_data[plot_data['model'] == model_name]['Predicted_Close_next']
            plt.plot(model_predictions, label=f'Predicted: {model_name}', linestyle='--')

        # 4. ปรับแต่งกราฟ
        plt.title(f'Forecast vs. Actual Price for {TARGET_SYMBOL} (Window ID: {max_window})', fontsize=16)
        plt.xlabel('Date', fontsize=12)
        plt.ylabel('Price (USD)', fontsize=12)
        plt.legend(loc='upper left')
        plt.grid(True, alpha=0.5)
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

# 1. อ่านไฟล์ Excel สรุปผลลัพธ์เฉลี่ย
file_path_avg = "average_results_ActualOnly_lag7.xlsx"
try:
    average_results = pd.read_excel(file_path_avg)
except FileNotFoundError:
    print(f"❌ Error: File not found at {file_path_avg}. Please ensure the full code was run successfully.")
    average_results = pd.DataFrame()

if not average_results.empty:
    # ตั้งค่าโมเดลเป็น Index เพื่อให้ง่ายต่อการ Plot
    average_results = average_results.set_index('model')

    # กำหนดสีสำหรับแต่ละโมเดล
    model_colors = {
        'Linear': '#1f77b4',       # Blue
        'RandomForest': '#ff7f0e', # Orange
        'GradientBoosting': '#2ca02c', # Green
        'XGBoost': '#d62728',      # Red
        'SVR': '#9467bd'           # Purple
    }

    # เรียงลำดับโมเดลตามชื่อเพื่อให้สีคงที่
    models = average_results.index.tolist()
    colors = [model_colors.get(m, 'gray') for m in models]

    # --- กราฟที่ 1: เปรียบเทียบ RMSE ---
    plt.figure(figsize=(12, 6))

    # สร้างกราฟแท่ง
    bars = plt.bar(models, average_results['rmse'], color=colors)

    # เพิ่มค่าตัวเลขบนแท่งกราฟ
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2.0, yval + 0.01, f'{yval:.4f}', ha='center', va='bottom', fontsize=10)

    plt.title('Average RMSE Comparison Across 5 Models (Actual Dates Only)', fontsize=16)
    plt.xlabel('Forecasting Model', fontsize=12)
    plt.ylabel('Average RMSE', fontsize=12)
    plt.grid(axis='y', alpha=0.5)
    plt.show()

    # --- กราฟที่ 2: เปรียบเทียบ R² ---
    plt.figure(figsize=(12, 6))

    # สร้างกราฟแท่ง
    bars = plt.bar(models, average_results['r2'], color=colors)

    # เพิ่มค่าตัวเลขบนแท่งกราฟ
    for bar in bars:
        yval = bar.get_height()
        plt.text(bar.get_x() + bar.get_width()/2.0, yval + 0.0005, f'{yval:.4f}', ha='center', va='bottom', fontsize=10)

    plt.title('Average R-squared (R²) Comparison Across 5 Models (Actual Dates Only)', fontsize=16)
    plt.xlabel('Forecasting Model', fontsize=12)
    plt.ylabel('Average R²', fontsize=12)
    plt.ylim(average_results['r2'].min() - 0.005, 1.0) # กำหนดแกน y ให้เห็นความแตกต่างชัดเจนขึ้น
    plt.grid(axis='y', alpha=0.5)
    plt.show()

# -*- coding: utf-8 -*-
"""Model-5-Lag7_TechIndicators_ActualOnly.ipynb
---
วัตถุประสงค์: รวม Lag-7 และ Technical Indicators (SMA, RSI, MACD) เป็น Features
และประเมินผลเฉพาะวันทำการจริง (Actual Dates Only)
"""

# ----------------------------------------------------
# 0. ติดตั้งและนำเข้าไลบรารี
# ----------------------------------------------------
!pip install pandas_market_calendars
!pip install yfinance scikit-learn xgboost matplotlib tqdm

import yfinance as yf
import pandas as pd
import numpy as np
from datetime import datetime
import pandas_market_calendars as mcal
from tqdm import tqdm

# ไลบรารีสำหรับ Machine Learning
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from xgboost import XGBRegressor
from sklearn.svm import SVR
from sklearn.metrics import mean_squared_error, r2_score, mean_absolute_error
from sklearn.preprocessing import StandardScaler

# ------------------------------
# 0. กำหนด list หุ้นทั้งหมด และช่วงวันที่
# ------------------------------
tickers = ["AAPL", "AMD", "AVGO", "GOOG", "GOOGL", "META", "MSFT", "NVDA"]
start_date = datetime(2019, 1, 1)
end_date   = datetime(2024, 12, 31)
all_data_list = []

# ------------------------------
# 1. ดาวน์โหลดข้อมูลหุ้นทั้งหมด
# ------------------------------
for ticker in tickers:
    print(f"📥 Downloading {ticker} ...")
    data = yf.download(ticker, start=start_date.strftime('%Y-%m-%d'), end=end_date.strftime('%Y-%m-%d'))

    if data.empty:
        print(f"❌ No data for {ticker}")
        continue

    data.reset_index(inplace=True)

    if isinstance(data.columns, pd.MultiIndex):
        data.columns = [' '.join(col).strip() if isinstance(col, tuple) else col for col in data.columns.values]

    def clean_columns(cols):
        cleaned = []
        for col in cols:
            if 'Date' in col: cleaned.append('Date')
            else: cleaned.append(col.split()[0])
        return cleaned

    data.columns = clean_columns(data.columns)
    data['Symbol'] = ticker.upper()

    wanted_cols = ['Date', 'Open','High','Low','Close', 'Volume', 'Symbol']
    data = data[[col for col in wanted_cols if col in data.columns]]
    all_data_list.append(data)

flat_df = pd.concat(all_data_list, ignore_index=True)
print("✅ ดาวน์โหลดและรวมข้อมูลสำเร็จ")

# ----------------------------------------------------
# 2. จัดการวันหยุด + Nearest Neighbor Interpolation และสร้าง Flag
# ----------------------------------------------------
# 1. สร้าง continuous date range
all_dates = pd.DataFrame({'Date': pd.date_range(flat_df['Date'].min(), flat_df['Date'].max())})
symbols = flat_df['Symbol'].unique()
expanded_list = []
for sym in symbols:
    temp = all_dates.copy()
    temp['Symbol'] = sym
    expanded_list.append(temp)
all_dates_symbols = pd.concat(expanded_list, ignore_index=True)

# 2. merge กับ flat_df (ตอนนี้ 'Close' มี NaN ในวันหยุด)
full_df = all_dates_symbols.merge(flat_df, on=['Date','Symbol'], how='left')

# สร้าง Flag สำหรับราคาปิดจริง (Actual Close)
full_df['Is_Actual_Close'] = full_df['Close'].notna().astype(float)

# 3. เติมค่าว่าง Close ด้วย nearest (Interpolation)
price_cols = ['Close']
for col in price_cols:
    full_df[col] = full_df.groupby('Symbol')[col].transform(
        lambda x: x.interpolate(method='nearest')
    )
full_df[['Open','High','Low','Volume']] = full_df[['Open','High','Low','Volume']].fillna(0)

print("\n✅ จัดการวันหยุดและ Nearest Neighbor Interpolation เสร็จสิ้น")

# ----------------------------------------------------
# 3. สร้าง Lag-7 Features และ Technical Indicators
# ----------------------------------------------------

# 3.1 สร้าง Lag-7 Features
lag_cols = []
for lag in range(1, 8):
    col_name = f'Close_lag{lag}'
    full_df[col_name] = full_df.groupby('Symbol')['Close'].shift(lag)
    lag_cols.append(col_name)

# 3.2 สร้าง Technical Indicators
def calculate_technical_indicators(df):
    """คำนวณ SMA, RSI, และ MACD โดยใช้ราคา Close ที่ถูก Interpolate แล้ว"""

    # คำนวณ Simple Moving Average (SMA)
    df['SMA_10'] = df.groupby('Symbol')['Close'].transform(lambda x: x.rolling(window=10).mean())
    df['SMA_50'] = df.groupby('Symbol')['Close'].transform(lambda x: x.rolling(window=50).mean())

    # คำนวณ Relative Strength Index (RSI - 14 วัน)
    def calculate_rsi(series, window=14):
        # ใช้ราคา Close ที่ Interpolate แล้ว
        diff = series.diff().dropna()
        gain = (diff.where(diff > 0, 0)).rolling(window=window).mean()
        loss = (-diff.where(diff < 0, 0)).rolling(window=window).mean()
        rs = gain / loss
        rsi = 100 - (100 / (1 + rs))
        return rsi.fillna(50.0) # RSI เริ่มต้นให้เติมค่ากลาง 50.0 หรือตามวิธีการที่กำหนด

    df['RSI'] = df.groupby('Symbol')['Close'].transform(calculate_rsi)

    # คำนวณ Moving Average Convergence Divergence (MACD)
    df['EMA_12'] = df.groupby('Symbol')['Close'].transform(lambda x: x.ewm(span=12, adjust=False).mean())
    df['EMA_26'] = df.groupby('Symbol')['Close'].transform(lambda x: x.ewm(span=26, adjust=False).mean())
    df['MACD'] = df['EMA_12'] - df['EMA_26']

    return df

full_df = calculate_technical_indicators(full_df)

# 3.3 สร้าง Target และ Flag
full_df['Close_next'] = full_df.groupby('Symbol')['Close'].shift(-1)
full_df['Is_Actual_Target'] = full_df.groupby('Symbol')['Is_Actual_Close'].shift(-1)

# กำหนด Feature Matrix X ใหม่
tech_cols = ['SMA_10', 'SMA_50', 'RSI', 'MACD']
X_cols = lag_cols + tech_cols

# เติมค่า NaN ที่เกิดจากการคำนวณ Indicators (ช่วงเริ่มต้น) ด้วย 0.0
# แถวเหล่านี้จะถูก dropna() ในขั้นตอน Sliding Window
full_df[tech_cols] = full_df[tech_cols].fillna(0.0)

print(f"\n✅ สร้าง Features ทั้งหมดเสร็จสิ้น: {len(X_cols)} Features")
print(f"Features List: {X_cols}")


# ----------------------------------------------------
# 4. Sliding Window (70/15/15) และ Model Training/Evaluation
# ----------------------------------------------------
window_train = 0.7
window_test = 0.15

# เตรียมโมเดล (5 โมเดล)
models = {
    'Linear': LinearRegression(),
    'RandomForest': RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1),
    'GradientBoosting': GradientBoostingRegressor(n_estimators=100, random_state=42),
    'XGBoost': XGBRegressor(n_estimators=100, random_state=42, verbosity=0, n_jobs=-1),
    'SVR': SVR()
}

all_results = []
window_predictions_full = []
# ***เปลี่ยนชื่อสำหรับ Export ไฟล์ใหม่***
model_name = "Lag7_TechIndicators_ActualOnly"

# Loop แต่ละ Symbol
for sym in tqdm(symbols, desc="Training models with Lag-7 + Tech Indicators"):
    df_sym = full_df[full_df['Symbol'] == sym].sort_values('Date').reset_index(drop=True)

    # Feature, Target และ Flag
    data_ml = df_sym[['Date'] + X_cols + ['Close_next', 'Is_Actual_Target']].dropna().reset_index(drop=True)

    X_clean = data_ml[X_cols]
    y_clean = data_ml['Close_next']
    is_actual_target_clean = data_ml['Is_Actual_Target']
    date_clean = data_ml['Date']

    n = len(X_clean)
    step = int(n * window_test)
    start = 0
    window_id = 1

    # Sliding Window Loop
    while start + int(n * window_train) + step <= n:
        train_idx = range(start, start + int(n*window_train))
        test_idx  = range(start + int(n*window_train), start + int(n*window_train) + step)

        X_train = X_clean.iloc[train_idx].values
        y_train = y_clean.iloc[train_idx].values
        X_test  = X_clean.iloc[test_idx].values
        y_test  = y_clean.iloc[test_idx].values

        is_actual_test = is_actual_target_clean.iloc[test_idx].values
        date_test = date_clean.iloc[test_idx].values

        # Scale Training set
        scaler = StandardScaler()
        X_train_scaled = scaler.fit_transform(X_train)
        X_test_scaled  = scaler.transform(X_test)

        # Train & Evaluate ทุกโมเดล
        for name, model in models.items():
            model.fit(X_train_scaled, y_train)
            y_pred = model.predict(X_test_scaled)

            # การกรอง: ประเมินเฉพาะ Target ที่เป็นราคาจริงเท่านั้น (Is_Actual_Target = 1.0)
            actual_mask = (is_actual_test == 1.0)
            y_test_actual = y_test[actual_mask]
            y_pred_actual = y_pred[actual_mask]

            if len(y_test_actual) > 0:
                 # คำนวณ Metrics บนข้อมูลจริงเท่านั้น
                 all_results.append({
                    'Symbol': sym,
                    'model': name,
                    'Window': window_id,
                    'start_idx': start,
                    'rmse': np.sqrt(mean_squared_error(y_test_actual, y_pred_actual)),
                    'mae': mean_absolute_error(y_test_actual, y_pred_actual),
                    'r2': r2_score(y_test_actual, y_pred_actual),
                    'Model Name': model_name
                 })

            # เก็บรายละเอียดการทำนาย (Predicted vs. Actual)
            temp_df = pd.DataFrame({
                'Date': date_test,
                'Symbol': sym,
                'Window': window_id,
                'model': name,
                'Actual_Close_next': y_test,
                'Predicted_Close_next': y_pred,
                'Is_Actual_Target': is_actual_test
            })
            window_predictions_full.append(temp_df)

        start += step
        window_id += 1

# แปลงเป็น DataFrame
results_df = pd.DataFrame(all_results)
window_predictions_df = pd.concat(window_predictions_full, axis=0).reset_index(drop=True)

print("\n✅ ฝึกฝนโมเดลและเก็บผลลัพธ์สำเร็จ")

# ----------------------------------------------------
# 5. สรุปและ Export ผลลัพธ์
# ----------------------------------------------------

# Export results_df (ผลลัพธ์ของทุก Window)
results_df.to_excel("results_TechIndicators_ActualOnly.xlsx", index=False)
print("✅ Exported results (Tech Indicators) to results_TechIndicators_ActualOnly.xlsx")

# สรุปผลลัพธ์ (Average Metrics)
average_results = results_df.groupby('model')[['rmse', 'mae', 'r2']].mean().reset_index()

# จัดรูปแบบตัวเลข
format_mapping = {
    'rmse': '{:,.4f}'.format,
    'mae': '{:,.4f}'.format,
    'r2': '{:,.4f}'.format
}
average_results_formatted = average_results.copy()
for col, formatter in format_mapping.items():
    average_results_formatted[col] = average_results_formatted[col].apply(formatter)

print("\n--- 📈 สรุปผลการประเมินโมเดล (Lag-7 + Tech Indicators) ---")
print(average_results_formatted)

# บันทึกผลสรุปค่าเฉลี่ยลงใน Excel
average_results.to_excel("average_results_TechIndicators_ActualOnly.xlsx", index=False)
print("✅ บันทึกผลสรุปค่าเฉลี่ยลงใน average_results_TechIndicators_ActualOnly.xlsx")

print("\n--- การรันโค้ดทั้งหมดเสร็จสมบูรณ์ ---")